site_name: TimeWarPY
nav:
  - Home: index.md
  - Examples and Usage: examples.md
  - Code Reference:
    - Preprocess: preprocess-reference.md
    - Datasets: datasets-reference.md
theme:
  features:
    - content.code.annotate
  name: "material"
plugins:
  - search
  - mkdocstrings
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
