site_name: TimeWarPY
site_url: https://timewarpy.readthedocs.io/en/latest/
nav:
  - Home: index.md
  - Code Reference:
    - Preprocess: preprocess-reference.md
theme: readthedocs
plugins:
  - search
  - mkdocstrings
